import { collisionName, folderHint, lodName, materialName, meshName, textureSet } from "./naming";
import { atlasSize } from "./pipeline";
import type { AssetSpec } from "./types";

/**
 * Python generators for Blender 4.2+ (tested on 5.2 LTS).
 *
 * Every runtime string is embedded as a JSON literal, which is also a valid
 * Python literal, and comment text is flattened to one line, so a brief cannot
 * break the script or inject code. Numbers are checked for finiteness.
 */

function py(value: string): string {
  return JSON.stringify(value);
}

function comment(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim();
}

function num(value: number, fallback = 0): string {
  return Number.isFinite(value) ? String(value) : String(fallback);
}

const SMOOTH_ANGLE_DEG = 35;

/** Bevel width in metres and segment count per kind. Organic kinds get none. */
const BEVEL: Partial<Record<AssetSpec["kind"], [number, number]>> = {
  crate: [0.012, 2],
  sci_crate: [0.018, 2],
  chest: [0.01, 2],
  ammo_can: [0.006, 2],
  barrel: [0.006, 1],
  pillar: [0.01, 1],
  wall: [0.01, 1],
  door: [0.01, 1],
  vent: [0.006, 1],
  stairs: [0.01, 1],
  sword: [0.002, 2],
  dagger: [0.0015, 2],
  pistol: [0.003, 2],
  rifle: [0.004, 2],
  shotgun: [0.004, 2],
  shield: [0.01, 2],
  pipe: [0.006, 1],
  lantern: [0.004, 1],
  hoverbike: [0.03, 2],
};

export function blenderScript(spec: AssetSpec): string {
  const mesh = meshName(spec);
  const col = collisionName(spec);
  const tex = textureSet(spec);
  const { x, y, z } = spec.dimensions;
  const bevel = BEVEL[spec.kind];
  const materials = spec.materials
    .map(
      (m) =>
        `    {"name": ${py(materialName(spec, m.name))}, "slot": ${py(m.slot)}, "albedo": ${py(m.albedo)}, "roughness": ${num(m.roughness, 0.5)}, "metallic": ${num(m.metalness, 0)}, "emissive": ${m.emissive ? py(m.emissive) : "None"}, "emissive_strength": ${num(m.emissiveIntensity ?? 1, 1)}},`,
    )
    .join("\n");

  return `# Anvil production script — ${comment(mesh)}
# Target: ${comment(spec.engine)} · ${comment(spec.style)} · ${comment(spec.units)}
# Brief: ${comment(spec.brief)}
# Generated by Anvil MCP for Blender 4.2+ (tested on 5.2 LTS).
# Builds into its own "Anvil_<mesh>" collection and never touches objects outside it.
# Re-running replaces the previous build. Set ANVIL_EXPORT_PATH (env) or EXPORT_PATH
# below to write a GLB when the build finishes. Set ANVIL_RIG=1 (or RIG_PARTS below) to add
# an armature with a bone per moving part and demo clips, for kinds the part kit covers.
# Material slots: the primary material covers the mesh; multi-part blockouts give each
# part its own slot; otherwise trim goes on bevelled edges, emissive on top faces,
# secondary on bottom faces and glass on side faces, so every slot survives export.

import json
import os
import bpy
import bmesh
from math import pi, radians
from mathutils import Vector

D = bpy.data
C = bpy.context

MESH = ${py(mesh)}
KIND = ${py(spec.kind)}
ENGINE = ${py(spec.engine)}
PIVOT = ${py(spec.pivot)}
COLLISION = ${py(spec.collision)}
COL_NAME = ${py(col)}
LOD_NAMES = (${py(lodName(spec, 1))}, ${py(lodName(spec, 2))})
LOD_BUDGET = (${num(spec.triangleBudget.lod1, 600)}, ${num(spec.triangleBudget.lod2, 200)})
LOD0_BUDGET = ${num(spec.triangleBudget.lod0, 2000)}
DIM = Vector((${num(x, 1)}, ${num(z, 1)}, ${num(y, 1)}))  # Blender X width, Y depth, Z height (the spec is Y-up)
BEVEL = ${bevel ? `(${num(bevel[0])}, ${num(bevel[1])})` : "None"}
SMOOTH_ANGLE = radians(${SMOOTH_ANGLE_DEG})
USING_KIT = False  # set when the Anvil add-on's part kit builds this kind
RIG_PARTS = os.environ.get("ANVIL_RIG", "").lower() in ("1", "true", "yes")  # armature + bones for the kit's moving parts
UNWRAP_ANGLE = radians(66)
EXPORT_PATH = os.environ.get("ANVIL_EXPORT_PATH", "")
TEX_NOTES = ${py(tex.notes)}
MATERIALS = [
${materials}
]
# material slot per blockout part, for the multi-part kinds (index into MATERIALS)
PART_SLOTS = {
    "sword": (0, 2, 1),
    "dagger": (0, 2, 1),
    "pistol": (0, 1),
    "rifle": (0, 1, 2, 1),
    "shotgun": (0, 1, 2, 1),
    "pipe": (0, 1),
    "hoverbike": (0, 2, 1, 1, 1, 1),
}

if bpy.app.version < (4, 1, 0):
    print("Anvil: this script targets Blender 4.1+; older versions may differ.")


# --- helpers -----------------------------------------------------------------

def srgb_to_linear(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear(hex_color):
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    return (srgb_to_linear(r), srgb_to_linear(g), srgb_to_linear(b), 1.0)


def select_none():
    if C.object is not None and C.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")


def select_only(ob):
    select_none()
    ob.select_set(True)
    C.view_layer.objects.active = ob


def layer_collection_for(coll, layer=None):
    layer = layer or C.view_layer.layer_collection
    if layer.collection == coll:
        return layer
    for child in layer.children:
        found = layer_collection_for(coll, child)
        if found is not None:
            return found
    return None


def prepare_collection():
    name = "Anvil_" + MESH
    coll = D.collections.get(name)
    if coll is None:
        coll = D.collections.new(name)
    if coll.name not in {c.name for c in C.scene.collection.children_recursive}:
        C.scene.collection.children.link(coll)
    for ob in list(coll.objects):
        data = ob.data
        D.objects.remove(ob, do_unlink=True)
        if isinstance(data, bpy.types.Mesh) and data.users == 0:
            D.meshes.remove(data)
        elif isinstance(data, bpy.types.Armature) and data.users == 0:
            D.armatures.remove(data)
    for mat in list(D.materials):
        if mat.get("anvil_mesh") == MESH and mat.users == 0:
            D.materials.remove(mat)
    layer = layer_collection_for(coll)
    if layer is not None:
        C.view_layer.active_layer_collection = layer
    return coll


def make_material(mat_spec):
    mat = D.materials.new(mat_spec["name"])
    if bpy.app.version < (5, 0, 0):  # 5.x materials are always node-based; touching use_nodes there warns
        mat.use_nodes = True
    nodes = mat.node_tree.nodes
    bsdf = next((n for n in nodes if n.type == "BSDF_PRINCIPLED"), None)
    if bsdf is None:
        bsdf = nodes.new("ShaderNodeBsdfPrincipled")
        out = next((n for n in nodes if n.type == "OUTPUT_MATERIAL"), None) or nodes.new("ShaderNodeOutputMaterial")
        mat.node_tree.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    bsdf.inputs["Base Color"].default_value = linear(mat_spec["albedo"])
    bsdf.inputs["Roughness"].default_value = mat_spec["roughness"]
    bsdf.inputs["Metallic"].default_value = mat_spec["metallic"]
    if mat_spec["emissive"]:
        bsdf.inputs["Emission Color"].default_value = linear(mat_spec["emissive"])
        bsdf.inputs["Emission Strength"].default_value = mat_spec["emissive_strength"]
    # viewport display (Solid shading and Workbench) mirrors the node values
    mat.diffuse_color = linear(mat_spec["albedo"])
    mat.metallic = mat_spec["metallic"]
    mat.roughness = mat_spec["roughness"]
    mat["anvil_mesh"] = MESH
    return mat


def add_box(size, center):
    bpy.ops.mesh.primitive_cube_add(size=1, location=center)
    ob = C.object
    ob.scale = size
    return ob


def add_cylinder(radius, depth, center, vertices=24, rotation=(0.0, 0.0, 0.0)):
    bpy.ops.mesh.primitive_cylinder_add(radius=radius, depth=depth, vertices=vertices, location=center, rotation=rotation)
    return C.object


def add_sphere(radius, center, scale=(1.0, 1.0, 1.0)):
    bpy.ops.mesh.primitive_uv_sphere_add(radius=radius, location=center, segments=24, ring_count=12)
    ob = C.object
    ob.scale = scale
    return ob


def join(parts):
    select_none()
    for part in parts:
        part.select_set(True)
    C.view_layer.objects.active = parts[0]
    if len(parts) > 1:
        merged = [part.data for part in parts[1:]]
        bpy.ops.object.join()
        for me in merged:  # the joined parts' meshes are orphans now; drop them so nothing keeps the materials alive
            if me.users == 0:
                D.meshes.remove(me)
    return C.object


def blockout(kind, dim):
    """Low-poly blockout whose bounding box equals the spec dimensions, resting on z = 0."""
    x, y, z = dim.x, dim.y, dim.z
    if kind in ("barrel", "pillar", "lantern"):
        return [add_cylinder(min(x, y) / 2, z, (0, 0, z / 2), vertices=24 if kind == "barrel" else 16)]
    if kind == "potion":
        r = min(x, y) / 2
        return [add_sphere(r, (0, 0, z / 2), scale=(1.0, 1.0, z / (2 * r)))]
    if kind == "helmet":
        r = x / 2
        return [add_sphere(r, (0, 0, z / 2), scale=(1.0, y / x, z / x))]
    if kind in ("sword", "dagger"):
        blade = z * 0.72
        return [
            add_box((x * 0.28, y, blade), (0, 0, z - blade / 2)),
            add_box((x, y * 0.8, z * 0.03), (0, 0, z * 0.265)),
            add_box((x * 0.2, y * 0.9, z * 0.25), (0, 0, z * 0.125)),
        ]
    if kind in ("pistol", "rifle", "shotgun"):
        body_h = z * (0.45 if kind == "pistol" else 0.4)
        grip_h = z - body_h
        parts = [
            add_box((x, y, body_h), (0, 0, z - body_h / 2)),
            add_box((x * 0.12, y, grip_h), (-x * (0.15 if kind == "pistol" else 0.2), 0, grip_h / 2)),
        ]
        if kind != "pistol":
            parts.append(add_box((x * 0.08, y * 0.8, grip_h * 0.8), (x * 0.05, 0, grip_h * 0.6)))
            parts.append(add_box((x * 0.25, y, body_h * 0.8), (-x * 0.375, 0, z - body_h * 0.6)))
        return parts
    if kind == "stairs":
        steps = 4
        depth = y / steps
        rise = z / steps
        return [
            add_box((x, depth, rise * (i + 1)), (0, -y / 2 + depth * (i + 0.5), rise * (i + 1) / 2))
            for i in range(steps)
        ]
    if kind == "pipe":
        r = y / 2
        return [
            add_cylinder(r, x, (0, 0, z - r), vertices=16, rotation=(0.0, pi / 2, 0.0)),
            add_cylinder(r, z - r, (0, 0, (z - r) / 2), vertices=16),
        ]
    if kind == "hoverbike":
        hull = z * 0.45
        parts = [
            add_box((x, y, hull), (0, 0, z * 0.2 + hull / 2)),
            add_box((x * 0.35, y * 0.6, z * 0.35), (-x * 0.1, 0, z * 0.825)),
        ]
        for sx in (-1, 1):
            for sy in (-1, 1):
                parts.append(add_box((x * 0.18, y * 0.3, z * 0.2), (sx * x * 0.3, sy * y * 0.3, z * 0.1)))
        return parts
    return [add_box((x, y, z), (0, 0, z / 2))]


def world_bounds(ob):
    C.view_layer.update()  # matrix_world and bound_box are stale until the depsgraph re-evaluates
    pts = [ob.matrix_world @ Vector(c) for c in ob.bound_box]
    lo = Vector((min(p.x for p in pts), min(p.y for p in pts), min(p.z for p in pts)))
    hi = Vector((max(p.x for p in pts), max(p.y for p in pts), max(p.z for p in pts)))
    return lo, hi


def move_origin(ob, target):
    select_only(ob)
    cursor = C.scene.cursor
    saved = cursor.location.copy()
    cursor.location = target
    bpy.ops.object.origin_set(type="ORIGIN_CURSOR")
    cursor.location = saved


def set_pivot(ob, pivot):
    lo, hi = world_bounds(ob)
    center = (lo + hi) / 2
    target = Vector((center.x, center.y, lo.z)) if pivot == "bottom" else center
    move_origin(ob, target)
    ob.location = (0.0, 0.0, 0.0)
    C.view_layer.update()
    ob["anvil_origin_shift"] = [target.x, target.y, target.z]  # build coordinates minus this are mesh coordinates


def pack_uv_islands(margin):
    """Repack the active UV layer: bounding-box packing with cardinal rotation is as tight as
    smart_project's own layout here and costs nothing; the exact-shape packers take 10-30 s on
    meshes with hundreds of islands."""
    try:
        bpy.ops.uv.pack_islands(rotate=True, rotate_method="CARDINAL", scale=True, margin_method="FRACTION", margin=margin, shape_method="AABB")
    except TypeError:  # older packer without shape/rotation options
        bpy.ops.uv.pack_islands(rotate=True, margin=margin)


def unwrap(ob):
    select_only(ob)
    if not ob.data.uv_layers:
        ob.data.uv_layers.new(name="UVMap")
    for index, margin in ((0, 0.004), (1, 0.012)):  # UV0 texture set, UV1 lightmap (more padding)
        if len(ob.data.uv_layers) <= index:
            ob.data.uv_layers.new(name="UV1")
        ob.data.uv_layers.active_index = index
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.uv.smart_project(angle_limit=UNWRAP_ANGLE, island_margin=margin)
        pack_uv_islands(margin)
        bpy.ops.object.mode_set(mode="OBJECT")
    ob.data.uv_layers.active_index = 0


def triangle_count(ob):
    return sum(max(len(p.vertices) - 2, 0) for p in ob.data.polygons)


def evaluated_triangles(ob):
    depsgraph = C.evaluated_depsgraph_get()
    evaluated = ob.evaluated_get(depsgraph)
    me = evaluated.to_mesh()
    n = sum(max(len(p.vertices) - 2, 0) for p in me.polygons)
    evaluated.to_mesh_clear()
    return n


def assign_part_slots(parts):
    """Give every part the full material list (so join keeps indices) and its own slot."""
    slots = PART_SLOTS.get(KIND, ())
    for index, part in enumerate(parts):
        for mat in MATS:
            part.data.materials.append(mat)
        slot = min(slots[index] if index < len(slots) else 0, len(MATS) - 1)
        for poly in part.data.polygons:
            poly.material_index = slot
    return parts


def distribute_slots(ob, bevel_mod):
    """Route the slots no part uses onto faces by role, so each material is exported."""
    used = {p.material_index for p in ob.data.polygons}
    polys = list(ob.data.polygons)
    top = [p for p in polys if p.normal.z > 0.7]
    bottom = [p for p in polys if p.normal.z < -0.7]
    sides = [p for p in polys if abs(p.normal.z) < 0.5]
    bevel_taken = False
    for index, spec in enumerate(MATERIALS):
        if index in used:
            continue
        role = spec["slot"]
        if role == "trim" and bevel_mod is not None and not bevel_taken and not PART_SLOTS.get(KIND) and not USING_KIT:
            bevel_mod.material = index  # bevelled edges take the trim slot
            bevel_taken = True
            continue
        faces = {"emissive": top, "secondary": bottom, "glass": sides}.get(role, top)
        for p in faces:
            p.material_index = index


def kit_parts():
    """Parts from the Anvil add-on's part kit, when it is installed and has a family for this kind."""
    try:
        from anvil_blender_addon.kit import build_parts
    except ImportError:
        return None
    try:
        return build_parts(KIND, DIM, MATERIALS)
    except Exception as exc:  # a kit failure must never lose the asset: fall back to the blockout
        print("Anvil kit failed for", KIND, "- using the blockout:", exc)
        return None


def rest_pose(arm):
    """Put an armature back to its rest pose.

    The glTF exporter evaluates each NLA track while writing its clip and leaves the last one
    applied, so without this the asset is left deformed in the file you are working in and every
    measurement taken after the export is wrong."""
    if arm is None:
        return
    for pose_bone in arm.pose.bones:
        pose_bone.location = (0.0, 0.0, 0.0)
        pose_bone.rotation_euler = (0.0, 0.0, 0.0)
        pose_bone.rotation_quaternion = (1.0, 0.0, 0.0, 0.0)
        pose_bone.scale = (1.0, 1.0, 1.0)
    C.view_layer.update()


def rig_parts(body, lods, rig_spec):
    """Armature with a bone per moving part, rigid skinning and demo clips, from the add-on's kit."""
    try:
        from anvil_blender_addon.kit import rig as kit_rig
    except ImportError:
        print("Anvil: ANVIL_RIG is set but the add-on's kit.rig is not importable; no rig")
        return None
    return kit_rig.apply(body, rig_spec, lods=lods, shift=body.get("anvil_origin_shift", (0.0, 0.0, 0.0)))


def finish_mesh(ob):
    ob.name = MESH
    ob.data.name = MESH
    select_only(ob)
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    bevel_mod = None
    if BEVEL is not None:
        bevel_mod = ob.modifiers.new("AnvilBevel", "BEVEL")
        bevel_mod.width = BEVEL[0]
        bevel_mod.segments = int(BEVEL[1])
        bevel_mod.limit_method = "ANGLE"
        bevel_mod.angle_limit = radians(30)
        bevel_mod.miter_outer = "MITER_ARC"
        bevel_mod.harden_normals = True
        wn = ob.modifiers.new("AnvilWN", "WEIGHTED_NORMAL")
        wn.keep_sharp = True
    bpy.ops.object.shade_smooth()
    if bpy.app.version >= (4, 1, 0):
        bpy.ops.object.shade_smooth_by_angle(angle=SMOOTH_ANGLE)
    elif hasattr(ob.data, "use_auto_smooth"):
        ob.data.use_auto_smooth = True
        ob.data.auto_smooth_angle = SMOOTH_ANGLE
    distribute_slots(ob, bevel_mod)
    unwrap(ob)
    set_pivot(ob, PIVOT)
    return ob


def convex_hull(body):
    depsgraph = C.evaluated_depsgraph_get()
    bm = bmesh.new()
    bm.from_object(body, depsgraph)
    hull = bmesh.ops.convex_hull(bm, input=bm.verts[:])
    seen = set()
    interior = []
    for g in hull["geom_interior"] + hull["geom_unused"]:  # the two lists overlap; deleting a vert twice raises
        if isinstance(g, bmesh.types.BMVert) and g.is_valid and id(g) not in seen:
            seen.add(id(g))
            interior.append(g)
    if interior:
        bmesh.ops.delete(bm, geom=interior, context="VERTS")
    bmesh.ops.dissolve_limit(bm, angle_limit=radians(5), verts=bm.verts[:], edges=bm.edges[:])
    me = D.meshes.new(COL_NAME)
    bm.to_mesh(me)
    bm.free()
    ob = D.objects.new(COL_NAME, me)
    COLL.objects.link(ob)
    ob.matrix_world = body.matrix_world.copy()
    return ob


def make_collision(body):
    lo, hi = world_bounds(body)
    size = hi - lo
    center = (lo + hi) / 2
    pad = 0.005
    if COLLISION == "sphere":
        bpy.ops.mesh.primitive_uv_sphere_add(radius=max(size) / 2 + pad, location=center, segments=16, ring_count=8)
        ob = C.object
    elif COLLISION == "capsule":
        bpy.ops.mesh.primitive_cylinder_add(radius=max(size.x, size.y) / 2 + pad, depth=size.z + 2 * pad, vertices=8, location=center)
        ob = C.object
    elif COLLISION == "convex":
        ob = convex_hull(body)
    else:
        bpy.ops.mesh.primitive_cube_add(size=1, location=center)
        ob = C.object
        ob.scale = (size.x + 2 * pad, size.y + 2 * pad, size.z + 2 * pad)
    ob.name = COL_NAME
    ob.data.name = COL_NAME
    select_only(ob)
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    # Quinn / prod hull budget: collision proxy ≤32 tris (capsule cylinder verts=8 → 28).
    COL_TRI_LIMIT = 32
    tris = triangle_count(ob)
    if tris > COL_TRI_LIMIT:
        mod = ob.modifiers.new("AnvilColDecimate", "DECIMATE")
        mod.ratio = max(0.05, COL_TRI_LIMIT / float(tris))
        mod.use_collapse_triangulate = True
        bpy.ops.object.modifier_apply(modifier="AnvilColDecimate")
    move_origin(ob, body.location)  # same pivot as the render mesh
    ob.display_type = "WIRE"
    ob.hide_render = True
    ob["anvil_collision"] = COLLISION
    return ob


def make_lod(body, name, budget):
    ob = body.copy()
    ob.data = body.data.copy()
    ob.name = name
    ob.data.name = name
    COLL.objects.link(ob)
    select_only(ob)
    for mod in list(ob.modifiers):
        bpy.ops.object.modifier_apply(modifier=mod.name)
    tris = triangle_count(ob)
    if tris > budget:
        mod = ob.modifiers.new("AnvilLOD", "DECIMATE")
        mod.ratio = max(0.05, budget / tris)
        mod.use_collapse_triangulate = True
        bpy.ops.object.modifier_apply(modifier="AnvilLOD")
    ob.display_type = "WIRE"
    ob.hide_render = True  # export-only copies; keeps them out of renders and bakes
    ob["anvil_lod_budget"] = budget
    return ob



def make_sockets(body, finishing):
    """Emit intentional socket Empties (FPS grip / hand_socket) that survive part join.

    Kit families declare build-space locations in finishing["sockets"]. Weapon kinds without
    a declared grip still get a mesh-local fallback Empty so pivot_weapon_or_rigged can pass
    without any post-export GLB patch.
    """
    declared = list((finishing or {}).get("sockets") or [])
    has_grip = any(
        (s.get("name") or "").lower() in ("grip", "hand_socket", "ik_hand", "weapon_root")
        for s in declared
    )
    if KIND in ("rifle", "shotgun", "pistol", "sword", "dagger") and not has_grip:
        declared.append({"name": "grip", "location": [0.0, 0.0, -abs(float(DIM.z)) * 0.12], "space": "mesh"})
    if not declared:
        return []
    shift = Vector(body.get("anvil_origin_shift", (0.0, 0.0, 0.0)))
    out = []
    for spec in declared:
        name = spec.get("name") or "grip"
        raw = Vector(spec.get("location") or (0.0, 0.0, 0.0))
        # Kit sockets are build coordinates; convert to mesh-local after set_pivot.
        local = raw if spec.get("space") == "mesh" else (raw - shift)
        empty = D.objects.new(name, None)
        empty.empty_display_type = "SPHERE"
        empty.empty_display_size = 0.02
        COLL.objects.link(empty)
        empty.parent = body
        empty.location = local
        empty["anvil_socket"] = name
        out.append(empty)
    return out


# --- build ---------------------------------------------------------------------

COLL = prepare_collection()
C.scene.unit_settings.system = "METRIC"
C.scene.unit_settings.scale_length = 1.0
MATS = [make_material(m) for m in MATERIALS]

kit = kit_parts()
kit_finishing = {}
if kit:
    USING_KIT = True
    hints = kit.get("finishing", {}) or {}
    kit_finishing = hints
    if hints.get("bevel") and BEVEL is not None:
        BEVEL = tuple(hints["bevel"])
    if hints.get("smooth_angle"):
        SMOOTH_ANGLE = radians(hints["smooth_angle"])
    for part in kit["parts"]:
        for mat in MATS:
            part.data.materials.append(mat)
    body = finish_mesh(join(kit["parts"]))
else:
    body = finish_mesh(join(assign_part_slots(blockout(KIND, DIM))))
collision = make_collision(body)
lod1 = make_lod(body, LOD_NAMES[0], LOD_BUDGET[0])
lod2 = make_lod(body, LOD_NAMES[1], LOD_BUDGET[1])

rig = None
if USING_KIT and kit.get("rig"):
    body["anvil_parts"] = json.dumps(kit["rig"])  # moving parts with pivots, axes and travel, for rigging later
    if RIG_PARTS:
        rig = rig_parts(body, (lod1, lod2), kit["rig"])

body["anvil_engine"] = ENGINE
body["anvil_texel"] = ${num(spec.texelDensity, 512)}
body["anvil_albedo"] = ${py(tex.albedo)}
body["anvil_normal"] = ${py(tex.normal)}
body["anvil_orm"] = ${py(tex.packed)}
body["anvil_folder"] = ${py(folderHint(spec))}
body["anvil_pivot"] = PIVOT
body["anvil_source"] = "kit" if USING_KIT else "blockout"

sockets = make_sockets(body, kit_finishing)

# Godot generates its own LODs at import and has no notion of an exported LOD chain, so shipping
# LOD1 and LOD2 as sibling nodes just draws three copies of the asset on top of each other. They
# stay in the .blend for anyone who wants them; the other engines read them from the file.
export_set = [body, collision] if ENGINE == "godot" else [body, lod1, lod2, collision]
if rig is not None:
    export_set.append(rig)
export_set.extend(sockets)
select_none()
for ob in export_set:
    ob.select_set(True)
C.view_layer.objects.active = body

if EXPORT_PATH:
    os.makedirs(os.path.dirname(os.path.abspath(EXPORT_PATH)), exist_ok=True)
    # NLA_TRACKS exports only this armature's stashed clips; the default exports every action in
    # the file that fits it, which hands each asset the clips of everything else forged this session.
    bpy.ops.export_scene.gltf(filepath=EXPORT_PATH, export_format="GLB", use_selection=True, export_apply=True, export_yup=True, export_animation_mode="NLA_TRACKS")
    rest_pose(rig)

summary = "{} built ({}) in collection {}: LOD0 {} tris (budget {}), {} {} tris, {} {} tris, collision {} ({}), pivot {}{}".format(
    MESH, "part kit" if USING_KIT else "blockout", COLL.name, evaluated_triangles(body), LOD0_BUDGET,
    lod1.name, triangle_count(lod1), lod2.name, triangle_count(lod2),
    collision.name, COLLISION, PIVOT,
    " -> exported " + EXPORT_PATH if EXPORT_PATH else "",
)
if rig is not None:
    summary += "; rigged: {} bones, clips {}".format(len(rig.data.bones) - 1, ", ".join(t.name for t in rig.animation_data.nla_tracks) or "none")
if sockets:
    summary += "; sockets: {}".format(", ".join(s.name for s in sockets))
result = summary
print("Anvil built", summary)
print("Export: File > Export > glTF 2.0 · GLB · selected objects · apply modifiers · +Y up (the export set is selected)")
print("Textures:", ${py(tex.albedo)}, ${py(tex.normal)}, ${py(tex.packed)})
print(TEX_NOTES)
`;
}

/** Wear and dirt amounts (0..1) for the surfacing recipes, from the asset's category and style. */
function weathering(spec: AssetSpec): { wear: number; dirt: number } {
  const base: Record<AssetSpec["category"], [number, number]> = {
    weapons: [0.5, 0.35],
    props: [0.45, 0.4],
    architecture: [0.55, 0.55],
    vehicles: [0.5, 0.45],
    characters: [0.3, 0.3],
  };
  const [wear, dirt] = base[spec.category] ?? [0.45, 0.35];
  const scale = spec.style === "stylized" || spec.style === "hand_painted" ? 0.6 : spec.style === "realistic" ? 1.1 : 1;
  const clamp = (v: number) => Math.round(Math.min(1, Math.max(0, v * scale)) * 100) / 100;
  return { wear: clamp(wear), dirt: clamp(dirt) };
}

export function bakeScript(spec: AssetSpec): string {
  const mesh = meshName(spec);
  const tex = textureSet(spec);
  const size = atlasSize(spec);
  const primary = spec.materials[0];
  const { wear, dirt } = weathering(spec);
  const slots = spec.materials
    .map(
      (m) =>
        `    {"name": ${py(materialName(spec, m.name))}, "recipe": "auto", "color": ${py(m.albedo)}, "roughness": ${num(m.roughness, 0.5)}, "metallic": ${num(m.metalness, 0)}, "emissive": ${m.emissive ? py(m.emissive) : "None"}, "emissive_strength": ${num(m.emissiveIntensity ?? 1, 1)}},`,
    )
    .join("\n");
  return `# Anvil bake — ${comment(mesh)}
# Surfaces ${comment(mesh)}. With the Anvil add-on installed it bakes mesh maps (AO, edges) from a
# denser high-poly copy, builds one procedural recipe per material slot (painted, blued or bare
# steel, polymer, rubber, wood, brass, leather, fabric, stone, moss, glass, generic), bakes albedo,
# roughness, metallic and a tangent normal, packs ${comment(tex.packed)} for ${comment(spec.engine)}, saves PNGs
# and wires the textures into the mesh's materials (recipes stay as <material>_recipe). Without
# the add-on it bakes a normal + AO with flat channels. Run after the Anvil build script.
# Edit BAKE_SIZE, BAKE_SAMPLES, SLOTS (recipe "auto" or a recipe name), WEAR and DIRT, or set
# ANVIL_TEXTURE_DIR (output folder) and ANVIL_EXPORT_PATH (re-export the GLB with textures).

import os
import traceback
import bpy
import numpy as np

D = bpy.data
C = bpy.context

MESH = ${py(mesh)}
ENGINE = ${py(spec.engine)}
NORMAL_IMG = ${py(tex.normal)}
PACKED_IMG = ${py(tex.packed)}
ALBEDO_IMG = ${py(tex.albedo)}
ALBEDO_HEX = ${py(primary?.albedo ?? "#808080")}
ROUGHNESS = ${num(primary?.roughness ?? 0.5, 0.5)}
METALLIC = ${num(primary?.metalness ?? 0, 0)}
TEX_NOTES = ${py(tex.notes)}
BAKE_SIZE = ${size}
BAKE_SAMPLES = 16
CAGE_EXTRUSION = 0.02
WEAR = ${num(wear, 0.45)}  # 0 factory fresh .. 1 beaten up: edge wear, chips, scratches
DIRT = ${num(dirt, 0.35)}  # 0 clean .. 1 filthy: cavity grime and dust on upward faces
SEED = ${Math.abs(Math.trunc(spec.seed ?? 0)) % 10000}
# one entry per material slot; "auto" picks the recipe from the name and metalness, or name one of
# painted_steel, blued_steel, bare_steel, polymer, rubber, wood, brass, leather, fabric, stone, moss, glass, generic
SLOTS = [
${slots}
]
OUT_DIR = os.environ.get("ANVIL_TEXTURE_DIR", "")
EXPORT_PATH = os.environ.get("ANVIL_EXPORT_PATH", "")


def select_none():
    if C.object is not None and C.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")


def select_only(ob):
    select_none()
    ob.select_set(True)
    C.view_layer.objects.active = ob


def new_image(name, data, alpha=False):
    old = D.images.get(name)
    if old is not None:
        D.images.remove(old)
    return D.images.new(name, BAKE_SIZE, BAKE_SIZE, alpha=alpha, float_buffer=False, is_data=data)


def surfacing_tool():
    """The Anvil add-on's surfacing module, when the add-on is installed."""
    try:
        from anvil_blender_addon import surfacing
    except ImportError:
        return None
    return surfacing


low = D.objects.get(MESH)
if low is None or low.type != "MESH":
    raise RuntimeError("Anvil: mesh " + MESH + " not found. Run the build script first.")
if not low.data.uv_layers:
    raise RuntimeError("Anvil: " + MESH + " has no UVs.")

if OUT_DIR:
    out_dir = OUT_DIR
elif D.filepath:
    out_dir = bpy.path.abspath("//textures")
else:
    out_dir = os.path.join(bpy.app.tempdir, "anvil_textures")
os.makedirs(out_dir, exist_ok=True)

# --- high-poly source: the same mesh with a denser bevel, or a subdivision for organic shapes
high = low.copy()
high.data = low.data.copy()
high.name = "HP_" + MESH
high.data.name = high.name
low.users_collection[0].objects.link(high)
bevels = [m for m in high.modifiers if m.type == "BEVEL"]
if bevels:
    for mod in bevels:
        mod.segments = max(mod.segments * 3, 6)
        mod.harden_normals = True
else:
    sub = high.modifiers.new("AnvilHP", "SUBSURF")
    sub.levels = 2
    sub.render_levels = 2
select_only(high)
for mod in list(high.modifiers):
    bpy.ops.object.modifier_apply(modifier=mod.name)
bpy.ops.object.shade_smooth()


def plain_bake():
    """Normal + AO from the high-poly with flat roughness, metallic and albedo: the bake used
    when the add-on's surfacing is not available. Returns the saved paths."""
    normal_img = new_image(NORMAL_IMG, True)
    ao_img = new_image("Anvil_AO_temp", True)
    targets = []
    for slot in low.material_slots:
        mat = slot.material
        if mat is None:
            continue
        if bpy.app.version < (5, 0, 0):  # see build script: use_nodes is deprecated on 5.x
            mat.use_nodes = True
        node = mat.node_tree.nodes.new("ShaderNodeTexImage")
        node.name = "AnvilBakeTarget"
        node.image = normal_img
        for other in mat.node_tree.nodes:
            other.select = False
        node.select = True
        mat.node_tree.nodes.active = node
        targets.append((mat, node))
    if not targets:
        raise RuntimeError("Anvil: " + MESH + " has no materials to bake into.")

    scene = C.scene
    previous_engine = scene.render.engine
    # bake in isolation: LOD copies, collision and anything else in the scene would occlude the AO rays
    hidden = []
    for other in scene.objects:
        if other not in (low, high) and not other.hide_render:
            other.hide_render = True
            hidden.append(other)
    scene.render.engine = "CYCLES"
    scene.cycles.samples = BAKE_SAMPLES
    settings = scene.render.bake
    settings.use_selected_to_active = True
    settings.cage_extrusion = CAGE_EXTRUSION
    settings.max_ray_distance = CAGE_EXTRUSION * 2
    settings.margin = max(4, BAKE_SIZE // 256)
    settings.normal_space = "TANGENT"
    settings.use_clear = True

    def bake(kind):
        select_none()
        high.select_set(True)
        low.select_set(True)
        C.view_layer.objects.active = low
        bpy.ops.object.bake(type=kind)

    bake("NORMAL")
    for mat, node in targets:
        node.image = ao_img
    bake("AO")

    # --- pack: ORM (R AO, G roughness, B metallic) or Unity HDRP Mask (R metallic, G AO, B detail, A smoothness)
    count = BAKE_SIZE * BAKE_SIZE
    ao = np.empty(count * 4, dtype=np.float32)
    ao_img.pixels.foreach_get(ao)
    ao = ao.reshape(count, 4)
    packed = np.ones((count, 4), dtype=np.float32)
    if ENGINE == "unity":
        packed[:, 0] = METALLIC
        packed[:, 1] = ao[:, 0]
        packed[:, 2] = 1.0
        packed[:, 3] = 1.0 - ROUGHNESS
        packed_img = new_image(PACKED_IMG, True, alpha=True)
    else:
        packed[:, 0] = ao[:, 0]
        packed[:, 1] = ROUGHNESS
        packed[:, 2] = METALLIC
        packed_img = new_image(PACKED_IMG, True)
    packed_img.pixels.foreach_set(packed.ravel())

    albedo_img = new_image(ALBEDO_IMG, False)
    r, g, b = (int(ALBEDO_HEX.lstrip("#")[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    albedo_img.pixels.foreach_set(np.tile(np.array([r, g, b, 1.0], dtype=np.float32), count))

    saved = []
    for img in (normal_img, packed_img, albedo_img):
        path = os.path.join(out_dir, img.name + ".png")
        img.filepath_raw = path
        img.file_format = "PNG"
        img.save(filepath=path)
        saved.append(path)

    # --- cleanup: leave the materials and scene as they were
    for mat, node in targets:
        mat.node_tree.nodes.remove(node)
    D.images.remove(ao_img)
    for other in hidden:
        other.hide_render = False
    scene.render.engine = previous_engine
    return saved


surfaced = None
tool = surfacing_tool()
if tool is not None:
    try:
        surfaced = tool.surface(
            low, high, slots=SLOTS, size=BAKE_SIZE, samples=BAKE_SAMPLES, out_dir=out_dir,
            names={"albedo": ALBEDO_IMG, "normal": NORMAL_IMG, "packed": PACKED_IMG},
            engine=ENGINE, wear=WEAR, dirt=DIRT, seed=SEED,
        )
    except Exception:  # never lose the bake to a recipe problem: fall back to the plain bake
        print("Anvil surfacing failed; using the plain bake:\\n" + traceback.format_exc())
        surfaced = None
saved = surfaced["saved"] if surfaced else plain_bake()

high_mesh = high.data
D.objects.remove(high, do_unlink=True)
D.meshes.remove(high_mesh)
select_only(low)

if surfaced and EXPORT_PATH:  # the GLB written by the build script has no textures yet
    select_none()
    lod_names = {low.name + "_LOD1", low.name + "_LOD2"}
    for ob in low.users_collection[0].objects:
        if ob.type not in ("MESH", "ARMATURE", "EMPTY"):  # rig + intentional grip/hand sockets
            continue
        if ENGINE == "godot" and ob.name in lod_names:
            continue  # see the build script: Godot makes its own LODs
        ob.select_set(True)
    C.view_layer.objects.active = low
    os.makedirs(os.path.dirname(os.path.abspath(EXPORT_PATH)), exist_ok=True)
    bpy.ops.export_scene.gltf(filepath=EXPORT_PATH, export_format="GLB", use_selection=True, export_apply=True, export_yup=True, export_animation_mode="NLA_TRACKS")
    # the exporter evaluates each clip as it writes it and leaves the last one applied
    arm = D.objects.get(low.get("anvil_rig") or "")
    if arm is not None:
        for pose_bone in arm.pose.bones:
            pose_bone.location = (0.0, 0.0, 0.0)
            pose_bone.rotation_euler = (0.0, 0.0, 0.0)
            pose_bone.rotation_quaternion = (1.0, 0.0, 0.0, 0.0)
            pose_bone.scale = (1.0, 1.0, 1.0)
        C.view_layer.update()
    select_only(low)

if surfaced:
    result = "Surfaced {} at {}px ({}) in {}s and wrote {}{}".format(
        MESH, BAKE_SIZE, ", ".join(name + "=" + recipe for name, recipe in surfaced["recipes"].items()), surfaced["seconds"],
        ", ".join(saved), " -> exported " + EXPORT_PATH if EXPORT_PATH else "",
    )
else:
    result = "Baked {}px normal + AO for {} and wrote {} (install the Anvil add-on for surfaced textures)".format(BAKE_SIZE, MESH, ", ".join(saved))
print("Anvil", result)
print(TEX_NOTES)
`;
}
