import type { CatalogItem } from "./types";

export const CATALOG: CatalogItem[] = [
  {
    kind: "crate",
    name: "Shipping crate",
    category: "props",
    blurb: "Pine planks, steel bands, 1 m cube.",
    brief:
      "Weathered pine shipping crate, 1×1×1 m, steel corner brackets and two hoop bands, production prop for a warehouse level.",
    style: "realistic",
    triangleBudget: { lod0: 2800, lod1: 920, lod2: 220 },
    texelDensity: 512,
    collision: "box",
    dimensions: { x: 1, y: 1, z: 1 },
  },
  {
    kind: "sci_crate",
    name: "Supply crate",
    category: "props",
    blurb: "Hard-surface, emissive lock, panel lines.",
    brief:
      "Sci-fi military supply crate, hard surface, beveled panels, warning stripe, emissive lock plate, 0.8 m.",
    style: "hard_surface",
    triangleBudget: { lod0: 3000, lod1: 990, lod2: 240 },
    texelDensity: 512,
    collision: "box",
    dimensions: { x: 0.8, y: 0.7, z: 0.8 },
  },
  {
    kind: "barrel",
    name: "Oil barrel",
    category: "props",
    blurb: "55-gallon drum, rust, rolling hoops.",
    brief: "Industrial 55-gallon oil drum, rusted paint, rolling hoops, lid bung, 0.88 m tall.",
    style: "realistic",
    triangleBudget: { lod0: 2400, lod1: 790, lod2: 190 },
    texelDensity: 512,
    collision: "capsule",
    dimensions: { x: 0.6, y: 0.88, z: 0.6 },
  },
  {
    kind: "chest",
    name: "Relic chest",
    category: "props",
    blurb: "Iron-banded loot chest with hasp.",
    brief: "Stylized iron-banded wooden loot chest with rounded lid, hasp, and corner bosses.",
    style: "stylized",
    triangleBudget: { lod0: 3000, lod1: 990, lod2: 240 },
    texelDensity: 512,
    collision: "box",
    dimensions: { x: 1.1, y: 0.7, z: 0.7 },
  },
  {
    kind: "ammo_can",
    name: "Ammo can",
    category: "props",
    blurb: "Pressed steel, latch, carry handle.",
    brief: "US-style pressed steel ammo can, olive drab, latch, wire handle, 0.3 m.",
    style: "realistic",
    triangleBudget: { lod0: 2400, lod1: 790, lod2: 190 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.28, y: 0.2, z: 0.18 },
  },
  {
    kind: "sword",
    name: "Longsword",
    category: "weapons",
    blurb: "Hero melee, fuller, wrapped grip.",
    brief:
      "Production longsword, 1.15 m, diamond cross-section blade with fuller, steel crossguard, leather wrap, disc pommel. Pivot at grip.",
    style: "realistic",
    triangleBudget: { lod0: 4000, lod1: 1320, lod2: 320 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.18, y: 1.15, z: 0.04 },
  },
  {
    kind: "dagger",
    name: "Dagger",
    category: "weapons",
    blurb: "Short blade, compact LOD stack.",
    brief: "Utility dagger, 0.45 m, drop-point blade, simple guard, wrapped grip.",
    style: "realistic",
    triangleBudget: { lod0: 2600, lod1: 850, lod2: 200 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.08, y: 0.45, z: 0.02 },
  },
  {
    kind: "pistol",
    name: "Sidearm",
    category: "weapons",
    blurb: "Polymer frame, steel slide.",
    brief:
      "Modern sidearm, polymer frame, steel slide, short barrel, magazine, iron sights. First-person friendly silhouette.",
    style: "hard_surface",
    triangleBudget: { lod0: 6000, lod1: 1980, lod2: 480 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.22, y: 0.14, z: 0.04 },
  },
  {
    kind: "rifle",
    name: "Infantry rifle",
    category: "weapons",
    blurb: "Receiver, rail, mag, stock.",
    brief:
      "Modular infantry rifle, 0.9 m, railed receiver, polymer stock, 30-round mag, handguard, flash hider.",
    style: "hard_surface",
    triangleBudget: { lod0: 8000, lod1: 2600, lod2: 650 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.9, y: 0.22, z: 0.07 },
  },
  {
    kind: "shotgun",
    name: "Combat shotgun",
    category: "weapons",
    blurb: "Pump, heat shield, ghost ring.",
    brief: "Pump combat shotgun, heat shield, ghost-ring sight, synthetic furniture.",
    style: "hard_surface",
    triangleBudget: { lod0: 8000, lod1: 2640, lod2: 640 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.95, y: 0.18, z: 0.06 },
  },
  {
    kind: "shield",
    name: "Kite shield",
    category: "weapons",
    blurb: "Heraldic face, steel rim, boss.",
    brief: "Kite shield, 1.2 m, wood face, steel rim and boss, leather straps on back.",
    style: "stylized",
    triangleBudget: { lod0: 3000, lod1: 990, lod2: 240 },
    texelDensity: 1024,
    collision: "box",
    dimensions: { x: 0.7, y: 1.2, z: 0.08 },
  },
  {
    kind: "helmet",
    name: "Closed helm",
    category: "weapons",
    blurb: "Visor, bevor, plume socket.",
    brief: "Closed great helm, visor slit, bevor, plume socket, padded interior implied.",
    style: "stylized",
    triangleBudget: { lod0: 4000, lod1: 1320, lod2: 320 },
    texelDensity: 1024,
    collision: "sphere",
    dimensions: { x: 0.28, y: 0.32, z: 0.3 },
  },
  {
    kind: "pillar",
    name: "Stone pillar",
    category: "architecture",
    blurb: "Base, shaft, capital. Modular kit.",
    brief: "Dungeon stone pillar, 4 m, plinth, fluted shaft, simple capital. Modular kit piece, 2 m grid.",
    style: "stylized",
    triangleBudget: { lod0: 2400, lod1: 790, lod2: 190 },
    texelDensity: 256,
    collision: "box",
    dimensions: { x: 0.8, y: 4, z: 0.8 },
  },
  {
    kind: "wall",
    name: "Wall module",
    category: "architecture",
    blurb: "2 m kit wall, trim, skirting.",
    brief: "2×3 m modular wall, stone blocks, skirting, cornice, even texel, grid-snapped.",
    style: "stylized",
    triangleBudget: { lod0: 2000, lod1: 660, lod2: 160 },
    texelDensity: 256,
    collision: "box",
    dimensions: { x: 2, y: 3, z: 0.3 },
  },
  {
    kind: "stairs",
    name: "Stair module",
    category: "architecture",
    blurb: "8-step run, 2 m rise, rail.",
    brief: "Modular stone stairs, 8 treads, 2 m rise, 2 m run, simple rail, collision per step optional box.",
    style: "stylized",
    triangleBudget: { lod0: 2400, lod1: 790, lod2: 190 },
    texelDensity: 256,
    collision: "convex",
    dimensions: { x: 1.6, y: 2, z: 2 },
  },
  {
    kind: "pipe",
    name: "Pipe junction",
    category: "architecture",
    blurb: "Industrial T-junction + flanges.",
    brief: "Industrial pipe T-junction with flanges, bolts, rusted steel, 0.4 m diameter.",
    style: "hard_surface",
    triangleBudget: { lod0: 2600, lod1: 850, lod2: 200 },
    texelDensity: 512,
    collision: "convex",
    dimensions: { x: 1.2, y: 0.8, z: 0.5 },
  },
  {
    kind: "door",
    name: "Bulkhead door",
    category: "architecture",
    blurb: "2.2 m hatch, wheel, rivets.",
    brief: "Sci-fi bulkhead door, 2.2 m, pressure wheel, riveted frame, window slit.",
    style: "hard_surface",
    triangleBudget: { lod0: 4000, lod1: 1320, lod2: 320 },
    texelDensity: 512,
    collision: "box",
    dimensions: { x: 1.4, y: 2.2, z: 0.18 },
  },
  {
    kind: "vent",
    name: "Vent module",
    category: "architecture",
    blurb: "Grille, frame, 1 m tile.",
    brief: "Ceiling vent module, 1 m, louvered grille, screw frame, trim-sheet friendly.",
    style: "hard_surface",
    triangleBudget: { lod0: 1600, lod1: 520, lod2: 220 },
    texelDensity: 512,
    collision: "box",
    dimensions: { x: 1, y: 0.12, z: 1 },
  },
  {
    kind: "lantern",
    name: "Oil lantern",
    category: "props",
    blurb: "Emissive flame, glass, bail.",
    brief: "Kerosene lantern, brass cage, glass chimney, emissive flame, hanging bail.",
    style: "stylized",
    triangleBudget: { lod0: 3000, lod1: 990, lod2: 240 },
    texelDensity: 1024,
    collision: "capsule",
    dimensions: { x: 0.18, y: 0.36, z: 0.18 },
  },
  {
    kind: "potion",
    name: "Potion flask",
    category: "props",
    blurb: "Glass, cork, emissive liquid.",
    brief: "Alchemy flask, green glass, cork, emissive liquid, 0.22 m. Pickup prop.",
    style: "stylized",
    triangleBudget: { lod0: 2000, lod1: 660, lod2: 160 },
    texelDensity: 1024,
    collision: "capsule",
    dimensions: { x: 0.1, y: 0.22, z: 0.1 },
  },
  {
    kind: "hoverbike",
    name: "Hover bike",
    category: "vehicles",
    blurb: "Blockout + hard-surface body.",
    brief:
      "Sci-fi hover bike, 2.4 m, twin thrusters, exposed cockpit, hard-surface body. Vehicle blockout with production silhouette.",
    style: "hard_surface",
    triangleBudget: { lod0: 8000, lod1: 2640, lod2: 640 },
    texelDensity: 512,
    collision: "convex",
    dimensions: { x: 2.4, y: 0.9, z: 1.0 },
  },
  {
    kind: "mannequin",
    name: "Hero mannequin",
    category: "characters",
    blurb: "A-pose blockout, UE mannequin scale.",
    brief:
      "A-pose hero mannequin, 1.8 m, Unreal mannequin proportions, game-ready blockout for armor fitting.",
    style: "stylized",
    triangleBudget: { lod0: 3000, lod1: 990, lod2: 240 },
    texelDensity: 1024,
    collision: "capsule",
    dimensions: { x: 0.55, y: 1.8, z: 0.3 },
  },
];

export function catalogByKind(kind: CatalogItem["kind"]): CatalogItem {
  return CATALOG.find((item) => item.kind === kind) ?? CATALOG[0];
}
