/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiForgedRouteImport } from './routes/api/forged'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgedRoute = ApiForgedRouteImport.update({
  id: '/api/forged',
  path: '/api/forged',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/forged': typeof ApiForgedRoute
  '/api/mcp': typeof ApiMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/forged': typeof ApiForgedRoute
  '/api/mcp': typeof ApiMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/forged': typeof ApiForgedRoute
  '/api/mcp': typeof ApiMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/forged' | '/api/mcp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/forged' | '/api/mcp'
  id: '__root__' | '/' | '/api/forged' | '/api/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiForgedRoute: typeof ApiForgedRoute
  ApiMcpRoute: typeof ApiMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forged': {
      id: '/api/forged'
      path: '/api/forged'
      fullPath: '/api/forged'
      preLoaderRoute: typeof ApiForgedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiForgedRoute: ApiForgedRoute,
  ApiMcpRoute: ApiMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
